### ISSUE TITLE
Unable to rename the fridge

### ISSUE THREAD

**Issue by Michel-Rotta** [KiameV/rimworld-rimfridge#20]
Hi,

I make a test on the 1.0.1964

I have just a bug when I try to rename a fridge. The box open and it was possible to write the nex name, but the save buton doesn't save the new name. 

Regards,
Michel

**Comment by KiameV** [comment]
Just tested on 1.0.1964 rev6
Built a 1x1, 2x1, and 4x4 rimfridge. Renamed each successfully "1x1", "2x1" and "4x4"

https://i.imgur.com/BSbgpH8.jpg
