### ISSUE TITLE
Would you please provide a build.

### ISSUE THREAD

**Issue by jinlan** [KiameV/rimworld-rimfridge#37]
My version is : e461750b73220207e3b787bba5ef0c2e5ab4418b
You have modified many .cs file. Contains many important fix. I really want to play the newest version.

**Comment by KiameV** [comment]
The newest release can be downloaded from here:
https://github.com/KiameV/rimworld-rimfridge/releases/tag/1.0

I do not re-create releases as it's a pain. I do update the `Last Updated`, `ModSync Version`, and zip files though.

Direct Download of the zip file is: https://github.com/KiameV/rimworld-rimfridge/releases/download/1.0/RimFridge.zip
