### ISSUE TITLE
Name changes on version updates make compatibility hard

### ISSUE THREAD

**Issue by lilwhitemouse** [KiameV/rimworld-rimfridge#47]
Please consider naming the mod "RimFridge" instead of "RimFridge - x.y".  The way the mod is set designed, it is very easy to add compatibility buildings (just add in the comp!) and such buildings transition smoothly across RW updates.

As it is, players must wait for each mod author (e.g., me) to have a chance to update their mods to reflect the name change.

**Comment by KiameV** [comment]
done

**Comment by lilwhitemouse** [comment]
Thanks!

I have updated Deep Storage and Project RimFactory, and hopefully they will continue to work seamlessly from now on :)

(In case you were wondering, a lot of people notice when they don't have their Deep Storage Freezers :smile:  It's a popular item!)
