### ISSUE TITLE
Hopper update disallows placement of fridge away from dispenser.

### ISSUE THREAD

**Issue by yoeds** [KiameV/rimworld-rimfridge#48]
Cannot place fridges away from dispenser spaces. 
Attempts to do so prompts the following dialogue: "Must be placed next to something that needs a hopper."
Unsure if due to mod conflict.

**Comment by yoeds** [comment]
Seems to resolve after:
1. Install
2. Load game (start new game or load save)
3. Restart game
4. Issue gone

**Comment by KiameV** [comment]
the initial release was problematic. It's been resolved.
