### ISSUE TITLE
Unpowered but still cold fridges don't freeze food

### ISSUE THREAD

**Issue by futrtrubl** [KiameV/rimworld-rimfridge#49]
Between 1.2.0.0 and 1.2.1.0 something changed such that an unpowered (solar flare) fridge (double wall fridge in my case), even if the temperature in it is still below freezing, no longer freezes perishables. Likewise a temperature between 0 and 10 C no longer slows rotting.
Edit: Further a powered fridge even if the temperature is greater than 0 will still freeze perishables, that includes setting the target temperature above ambient. Allows the power cost to be cheated.

**Comment by KiameV** [comment]
This has been addressed with the last updat - v1.2.1.1.
