### ISSUE TITLE
Error message when loading the mod

### ISSUE THREAD

**Issue by ddy987** [KiameV/rimworld-rimfridge#50]
https://gist.github.com/HugsLibRecordKeeper/ed856856f28d6cc3faceac4361dfb9ab

**Comment by KiameV** [comment]
Don't see any rimfridge specific errors in those logs. What's the error in game?

**Comment by ddy987** [comment]
![RimWorldWin64_M2qLj8epkb](https://user-images.githubusercontent.com/38022968/95697004-f2542200-0c02-11eb-94a8-3ac3d7e0a8b4.png)

**Comment by ddy987** [comment]
I get these two red lines to pop up whenever I try to load RimFridge with my other mods.

**Comment by KiameV** [comment]
Thanks.

Are you on linux by chance? That's the only think I can think of that might
be causing an issue but even then I've verified that the file's using
ASCII + linux new line characters so even in that case there shouldn't be
an issue.

If you open the Version.xml file does it have the following:

<?xml version="1.0" encoding="utf-8"?>
<VersionData>
    <overrideVersion>1.2.1.1</overrideVersion>
    <gitHubRepository>KiameV/rimworld-rimfridge</gitHubRepository>
</VersionData>

**Comment by KiameV** [comment]
Never mind it's likely the \r. I looked them up incorrectly the first time.
I've updated the download on the release page. Let me know if that fixes
the issue.

https://github.com/KiameV/rimworld-rimfridge/releases/download/current/RimFridge.zip

**Comment by KiameV** [comment]
^and also updated on steam

**Comment by ddy987** [comment]
It's fixed!  Thanks for the quick work!
