### ISSUE TITLE
Fridges not working in 1.0

### ISSUE THREAD

**Issue by lael-i** [KiameV/rimworld-rimfridge#52]
Hi, thanks for the great mod! I used to use it a while ago and it went great, but I reinstalled recently and none of my fridges work - they are at their target temperature, but meals stored inside them aren't refrigerated/frozen and start to spoil. I have tested this with and without mods, and am playing on version 1.0.2231

**Comment by lael-i** [comment]
I found the issue - disabling the latest version of HugsLib fixed it. Unfortunately this is not feasible for my current playthrough as a fix.

**Comment by KiameV** [comment]
I am only supporting the 1.2 version of this mod, sorry.
