### ISSUE TITLE
1.3 - Debug spam on startup 

### ISSUE THREAD

**Issue by thisischrys** [KiameV/rimworld-rimfridge#55]
Below is repeated 5 times for some reason

`Could not find type named SaveStorageSettings.CompProperties_SaveStorageSettings from node <li Class="SaveStorageSettings.CompProperties_SaveStorageSettings"><name>fridge</name></li>
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
Verse.DirectXmlToObject:ClassTypeOf<Verse.CompProperties> (System.Xml.XmlNode)
Verse.DirectXmlToObject:ObjectFromXml<Verse.CompProperties> (System.Xml.XmlNode,bool)
Verse.DirectXmlToObject:ListFromXml<Verse.CompProperties> (System.Xml.XmlNode)
Verse.DirectXmlToObject:ListFromXmlReflection<Verse.CompProperties> (System.Xml.XmlNode)
Verse.DirectXmlToObject:ObjectFromXml<System.Collections.Generic.List`1<Verse.CompProperties>> (System.Xml.XmlNode,bool)
Verse.DirectXmlToObject:ObjectFromXmlReflection<System.Collections.Generic.List`1<Verse.CompProperties>> (System.Xml.XmlNode,bool)
Verse.DirectXmlToObject:ObjectFromXml<Verse.ThingDef> (System.Xml.XmlNode,bool)
Verse.DirectXmlToObject:ObjectFromXmlReflection<Verse.ThingDef> (System.Xml.XmlNode,bool)
Verse.DirectXmlLoader:DefFromNode (System.Xml.XmlNode,Verse.LoadableXmlAsset)
Verse.LoadedModManager:ParseAndProcessXML (System.Xml.XmlDocument,System.Collections.Generic.Dictionary`2<System.Xml.XmlNode, Verse.LoadableXmlAsset>)
Verse.LoadedModManager:LoadAllActiveMods ()
Verse.PlayDataLoader:DoPlayLoad ()
Verse.PlayDataLoader:LoadAllPlayData (bool)
Verse.Root/<>c:<Start>b__6_1 ()
Verse.LongEventHandler:RunEventFromAnotherThread (System.Action)
Verse.LongEventHandler/<>c:<UpdateCurrentAsynchronousEvent>b__27_0 ()
System.Threading.ThreadHelper:ThreadStart_Context (object)
System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object)
System.Threading.ThreadHelper:ThreadStart ()
`

Loaded mods
![image](https://user-images.githubusercontent.com/2012611/125098761-9d810180-e0d7-11eb-81a3-d606af2d9122.png)

**Comment by KiameV** [comment]
This is known and has been addressed. Just fell off the front page on steam chat.
Thank you
