### ISSUE TITLE
Obsolete method patch detected by HugsLib 

### ISSUE THREAD

**Issue by karlkatzke** [KiameV/rimworld-rimfridge#60]
Getting [com.rimfridge.rimworld.mod] Patches on methods annotated as Obsolete were detected by HugsLib: RimWorld.FoodUtility.TryFindBestFoodSourceFor
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Warning (string)
HugsLib.Utils.HarmonyUtility:LogObsoleteMethodPatchErrors ()
HugsLib.Utils.HarmonyUtility:LogHarmonyPatchIssueErrors ()
(wrapper dynamic-method) Verse.LongEventHandler:Verse.LongEventHandler.ExecuteToExecuteWhenFinished_Patch2 ()
(wrapper dynamic-method) Verse.LongEventHandler:Verse.LongEventHandler.UpdateCurrentSynchronousEvent_Patch2 (bool&)
Verse.LongEventHandler:LongEventsUpdate (bool&)
(wrapper dynamic-method) Verse.Root:Verse.Root.Update_Patch1 (Verse.Root)
(wrapper dynamic-method) Verse.Root_Entry:Verse.Root_Entry.Update_Patch0 (Verse.Root_Entry)

**Comment by KiameV** [comment]
This repo is no longer maintained for RimWorld 1.4 and later.
