### ISSUE TITLE
Fridge as stockpile

### ISSUE THREAD

**Issue by ghost** [KiameV/rimworld-rimfridge#9]
Hello! Thanks for your work on this awesome mod!

Would it be possible to make the fridge storage count as stockpile? I'm asking that because it would make it easier to use through [Phi](https://github.com/Longwelwind/Phi).

At this moment it only shows up as inventory but it doesn't appear when I try to send items to other players through Phi.

Thanks!

**Comment by KiameV** [comment]
It is currently a stockpile at least as far what a building can be. Phi can probably do a search for things like rimfridge or change dresser and pick them up that way.

**Comment by OOZ662** [comment]
> It is currently a stockpile at least as far what a building can be.

Does that mean that nothing can be done to make RimFridges appear in the "Take to Stockpile" dialogue on the B19 bill menu?

**Comment by KiameV** [comment]
Correct
